services:
  - type: web
    name: fashion-clip-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: PORT
        value: 7860
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /health
    autoDeploy: true

